config/routes.rb
Cert::Application.routes.draw do
  resources :services

  resources :certificates

  resources :stores, :only => [:new, :create]

  #devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}
  #get 'facebook_callback', :to => 'omniauth_callbacks#facebook', :as => 'facebook_callback'
  devise_for :users#, :only => :omniauth_callbacks

  #get 'users/auth/:provider/callback' => 'authentications#create'
  #post 'users/auth/:provider/callback' => 'authentications#create'
  #get '/auth/:provider/signout' => 'authentications#signout'
  #post '/auth/:provider/signout' => 'authentications#signout'

  get 'users/auth/:provider/callback' => 'authentications#facebook_callback'

  #mount FarmTools::Engine, :at => 'address'

  #debug
  get 'test', :to => 'tests#fb', :as => 'test'

  root 'certificates#new'
  #root :to => 'tests#fb'
end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  belongs_to :user
  belongs_to :giver, :class_name => 'User'

  validates :service_count, :numericality => {:greater_than_or_equal_to => 0, :allow_nil => true}

  validate :amount_or_service, :service_count_if_service
  validate :created_with_a_higher_amount_than_store_minimum, :on => :create

  private
    def amount_or_service
      errors.add(:amount, 'please specify a dollar amount and/or select a Service') if amount.nil? && service_id.nil?
      errors.add(:service_id, 'please specify a dollar amount and/or select a Service') if amount.nil? && service_id.nil?
    end

    def service_count_if_service
      errors.add(:service_count, 'Please specify a number of Services') if service_id && service_count.nil?
    end

    def created_with_a_higher_amount_than_store_minimum
      errors.add(:amount, "must be more than the minimum of $#{Store.first.minimum_amount}") unless amount.nil? || amount >= Store.first.minimum_amount
    end
  public
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_action :set_certificate, only: [:show, :edit, :update, :destroy]

  # GET /certificates
  # GET /certificates.json
  def index
    @certificates = Certificate.all
  end

  # GET /certificates/1
  # GET /certificates/1.json
  def show
  end

  # GET /certificates/new
  def new
    @certificate = Certificate.new
  end

  # GET /certificates/1/edit
  def edit
  end

  # POST /certificates
  # POST /certificates.json
  def create
    @certificate = Certificate.new(certificate_params)

    respond_to do |format|
      if @certificate.save
        format.html { redirect_to @certificate, notice: 'Certificate was successfully created.' }
        format.json { render action: 'show', status: :created, location: @certificate }
      else
        format.html { render action: 'new' }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certificates/1
  # PATCH/PUT /certificates/1.json
  def update
    respond_to do |format|
      if @certificate.update(certificate_params)
        format.html { redirect_to @certificate, notice: 'Certificate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certificates/1
  # DELETE /certificates/1.json
  def destroy
    @certificate.destroy
    respond_to do |format|
      format.html { redirect_to certificates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificate
      @certificate = Certificate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certificate_params
      params.require(:certificate).permit(:user_id, :amount, :giver_id, :giver_name)
    end
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/certificates/_certificate_amount.html.erb
<div id="certificate_amount" class="form-group">
  <%= form_for(@certificate) do |f| %>
    <%= error_explanation(@certificate, :include_explanation => false) %><%= f.label :amount, 'Gift Amount', :class => 'control-label' %>

    <div class="input-group">
      <span class="input-group-addon">$</span>
      <%= f.text_field :amount, :class => 'form-control money_control',
                     :placeholder => "$#{store.minimum_amount} or more.." %>
      <span class="input-group-addon">.00</span>
    </div>
  <% end %>
</div><!--fg-->

app/views/certificates/_form.html.erb
<div class="row">
  <div class="col-md-3">
    <h2>From:</h2>
    <%= render partial: 'devise/current_user' %>
  </div><!--col-->

  <div class="col-md-6 well">
    <h2>To:</h2>
    <%= render partial: 'identify_recipient' %>
  </div><!--col-->

  <div class="col-md-3">
    <h2>For:</h2>
    <%= render :partial => 'certificate_amount' %>
  </div><!--col-->
</div><!--row-->

app/views/certificates/_identify_recipient.html.erb
<div id="identify_recipient">
  <% if user_signed_in? %>

  <% else %>
    <h4>
      Please Login or Sign up. You will be able to send your friends our gift certificates through Facebook, email, or regular mail.
    </h4>
  <% end %>
</div>

app/views/certificates/edit.html.erb
<h1>Editing certificate</h1>

<%= render 'form' %>

<%= link_to 'Show', @certificate %> |
<%= link_to 'Back', certificates_path %>

app/views/certificates/index.html.erb
<h1>Listing certificates</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Amount</th>
      <th>Giver</th>
      <th>Giver name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @certificates.each do |certificate| %>
      <tr>
        <td><%= certificate.user_id %></td>
        <td><%= certificate.amount %></td>
        <td><%= certificate.giver_id %></td>
        <td><%= certificate.giver_name %></td>
        <td><%= link_to 'Show', certificate %></td>
        <td><%= link_to 'Edit', edit_certificate_path(certificate) %></td>
        <td><%= link_to 'Destroy', certificate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Certificate', new_certificate_path %>

app/views/certificates/new.html.erb
<div id="new_certificate" class="container">
  <h1>Give Your Friend a Gift Certificate<br>
      From <%= store_name %></h1>
  <%= render 'form' %>
</div>

app/views/certificates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @certificate.user_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @certificate.amount %>
</p>

<p>
  <strong>Giver:</strong>
  <%= @certificate.giver_id %>
</p>

<p>
  <strong>Giver name:</strong>
  <%= @certificate.giver_name %>
</p>

<%= link_to 'Edit', edit_certificate_path(@certificate) %> |
<%= link_to 'Back', certificates_path %>